CREATE COLUMN TABLE "EXO_LOG_INTERCOMPANY" (
DATEPROCESS DATETIME NOT NULL, 
HORA NVARCHAR(5) NOT NULL,
BBDD NVARCHAR(50) NOT NULL, 
USUARIO NVARCHAR(50) NOT NULL,
MODELO NVARCHAR(50) NOT NULL,
TIPO NVARCHAR(10) NOT NULL,
MESSAGE CLOB MEMORY THRESHOLD 1000 NOT NULL 
) UNLOAD PRIORITY 5 AUTO MERGE
